firstapp/urls.py
from django.urls import path
from . import views

app_name = 'firstapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.crud.savedata, name='savedata'),
    path('<int:data_id>/edit/', views.crud.editdata, name='editdata'),
    path('update/', views.crud.updatedata, name='updatedata'),
    path('<int:data_id>/deletedata/', views.crud.deletedata, name='deletedata'),
]

learndjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstapp/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    name = models.CharField(max_length=200, blank=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    file = models.FileField(upload_to='files', blank=True)
    image = models.FileField(upload_to='images', blank=True)

    class Meta:
        db_table = u'firstapp_question'

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return self.image

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

firstapp/forms.py
from django import forms


class ImageForm(forms.Form):
    image = forms.FileField(
        label='Select a file'
    )

firstapp/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.conf import settings
import os
from .models import Question
import logging

# Setup logger
logger = logging.getLogger(__name__)

class IndexView(generic.ListView):
    template_name = 'firstapp/home.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')

class crud:  # Ensure this is lower case 'c'
    @staticmethod
    def savedata(request):
        sv = Question(name=request.POST['name'], question_text=request.POST['questiontext'], file=request.FILES['file'], image=request.FILES['image'], pub_date=timezone.now())
        sv.save()
        return HttpResponseRedirect(reverse('firstapp:index'))

    @staticmethod
    def editdata(request, data_id):
        data = get_object_or_404(Question, pk=data_id)
        alldata = Question.objects.order_by('-pub_date')
        return render(request, 'firstapp/home.html', {'data': data, 'qid': data_id, 'getdata': alldata})

    @staticmethod
    def updatedata(request):
        ed = Question.objects.get(id=request.POST['qid'])
        imagePath = os.path.join(settings.MEDIA_ROOT, ed.image.name)
        filePath = os.path.join(settings.MEDIA_ROOT, ed.file.name)

        if 'image' in request.FILES:
            ed.image = request.FILES['image']
            if os.path.isfile(imagePath):
                os.remove(imagePath)

        if 'file' in request.FILES:
            ed.file = request.FILES['file']
            if os.path.isfile(filePath):
                os.remove(filePath)

        ed.name = request.POST['name']
        ed.question_text = request.POST['questiontext']
        ed.save()

        return HttpResponseRedirect(reverse('firstapp:index'))

    @staticmethod
    def deletedata(request, data_id):
        dl = get_object_or_404(Question, id=data_id)
        imagePath = os.path.join(settings.MEDIA_ROOT, dl.image.name)
        filePath = os.path.join(settings.MEDIA_ROOT, dl.file.name)

        if os.path.isfile(imagePath):
            os.remove(imagePath)
            logger.info(f"Deleted image file at: {imagePath}")

        if os.path.isfile(filePath):
            os.remove(filePath)
            logger.info(f"Deleted file at: {filePath}")

        dl.delete()
        logger.info(f"Deleted Question object with id: {data_id}")

        return HttpResponseRedirect(reverse('firstapp:index'))

firstapp/templates/firstapp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'firstapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

firstapp/templates/firstapp/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" media="screen" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" media="screen" href="{% static 'css/dataTables.bootstrap.css' %}">
    <link rel="stylesheet" media="screen" href="{% static 'css/dataTables.tableTools.css' %}">
    <link rel="stylesheet" media="screen" href="{% static 'css/style.css' %}">
    <title>Faiz Derma Solutions</title>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Faiz Derma Solutions</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Formulir Pasien</div>
                    <div class="panel-body">
                        {% if qid %}
                            <form method="POST" action="{% url 'firstapp:updatedata' %}" enctype="multipart/form-data" accept-charset="UTF-8" class="test-form">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Nama pasien</label>
                                    <input required="required" class="form-control" placeholder="Tuliskan nama anda" name="name" type="text" value="{{ data.name }}">
                                </div>
                                <div class="form-group">
                                    <label for="questiontext">Keluhan</label>
                                    <input type="hidden" name="qid" value="{{ data.pk }}">
                                    <input required="required" class="form-control" value="{{ data.question_text }}" placeholder="Tuliskan Keluhan anda" name="questiontext" type="text">
                                </div>
                                <div class="form-group">
                                    <label for="image">Kartu Identitas</label>
                                    <input class="form-control" name="image" type="file">
                                    <img src="{{ MEDIA_URL }}{{ data.image }}" style="width: 200px;">
                                </div>
                                <div class="form-group">
                                    <label for="file">Gejala penyakit</label>
                                    <input class="form-control" name="file" type="file">
                                    <img src="{{ MEDIA_URL }}{{ data.file }}" style="width: 200px;">
                                </div>
                                <div class="form-group">
                                    <input class="btn btn-primary" type="submit" value="Update Question">
                                </div>
                            </form>
                        {% else %}
                            <form method="POST" action="{% url 'firstapp:savedata' %}" enctype="multipart/form-data" accept-charset="UTF-8" class="test-form">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Nama pasien</label>
                                    <input required="required" class="form-control" placeholder="Tuliskan nama anda" name="name" type="text" value="">
                                </div>
                                <div class="form-group">
                                    <label for="questiontext">Keluhan</label>
                                    <input required="required" class="form-control" value="" placeholder="Tulsikan keluhan anda" name="questiontext" type="text">
                                </div>
                                <div class="form-group">
                                    <label for="image">Kartu Identitas</label>
                                    <input required="required" class="form-control" name="image" type="file">
                                </div>
                                <div class="form-group">
                                    <label for="file">Gejala penyakit</label>
                                    <input required="required" class="form-control" name="file" type="file">
                                </div>
                                <div class="form-group">
                                    <input class="btn btn-primary" type="submit" value="Daftar">
                                </div>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-md-8 col-sm-8 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">List Pasien</div>
                    <div class="panel-body">
                        <table class="table table-striped table-bordered datatable" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Keluhan</th>
                                    <th>Kartu Identitas</th>
                                    <th>Gejala Penyakit</th>
                                    <th>Tanggal</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if latest_question_list %}
                                    {% for question in latest_question_list %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ question.name }}</td>
                                            <td>{{ question.question_text }}</td>
                                            <td><img src="{{ MEDIA_URL }}{{ question.image }}" style="width: 60px;"></td>
                                            <td><img src="{{ MEDIA_URL }}{{ question.file }}" style="width: 60px;"></td>
                                            <td>{{ question.pub_date }}</td>
                                            <td>
                                                <a href="{% url 'firstapp:editdata' question.id %}">Edit</a> | 
                                                <a onclick="return confirm('Are you sure want to delete?');" href="{% url 'firstapp:deletedata' question.id %}">Delete</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% elif getdata %}
                                    {% for question in getdata %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ question.name }}</td>
                                            <td>{{ question.question_text }}</td>
                                            <td><img src="{{ MEDIA_URL }}{{ question.image }}" style="width: 60px;"></td>
                                            <td><img src="{{ MEDIA_URL }}{{ question.file }}" style="width: 60px;"></td>
                                            <td>{{ question.pub_date }}</td>
                                            <td>
                                                <a href="{% url 'firstapp:editdata' question.id %}">Edit</a> | 
                                                <a onclick="return confirm('Are you sure want to delete?');" href="{% url 'firstapp:deletedata' question.id %}">Delete</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="7">No Data Available ..</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="muted credit">Django - UAS BAHASA PEMROGRAMAN 2 <a href="https://www.linkedin.com/in/faiz-pratama/">Muhammad Faiz Bintang Pratama 3337230040</a></p>
        </div>
    </footer>
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>

firstapp/templates/firstapp/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'firstapp/style.css' %}" />

{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
			<li><a href="{% url 'firstapp:detail' question.id %}">{{ question.question_text }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No Data are avaible.</p>
{% endif %}

firstapp/templates/firstapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>